// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDayblKWeIDCsN1Ko2KvS2DuzUhAscaUzQ',
    appId: '1:165943096205:web:8977ae7ddda8361e6143c4',
    messagingSenderId: '165943096205',
    projectId: 'quickcarttdanyi',
    authDomain: 'quickcarttdanyi.firebaseapp.com',
    storageBucket: 'quickcarttdanyi.firebasestorage.app',
    measurementId: 'G-PS2TXF3RZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcjsd9Pwy9uMlnrMtYl7orjLBPXW1mJNU',
    appId: '1:165943096205:android:94b35fa92015c2b86143c4',
    messagingSenderId: '165943096205',
    projectId: 'quickcarttdanyi',
    storageBucket: 'quickcarttdanyi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeSc7oO9OwodEaQrSsAgiyk-qUWq8XT9c',
    appId: '1:165943096205:ios:a8ac69fcb75081fd6143c4',
    messagingSenderId: '165943096205',
    projectId: 'quickcarttdanyi',
    storageBucket: 'quickcarttdanyi.firebasestorage.app',
    iosBundleId: 'com.example.quickcart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeSc7oO9OwodEaQrSsAgiyk-qUWq8XT9c',
    appId: '1:165943096205:ios:a8ac69fcb75081fd6143c4',
    messagingSenderId: '165943096205',
    projectId: 'quickcarttdanyi',
    storageBucket: 'quickcarttdanyi.firebasestorage.app',
    iosBundleId: 'com.example.quickcart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDayblKWeIDCsN1Ko2KvS2DuzUhAscaUzQ',
    appId: '1:165943096205:web:5a92008ccc59a77a6143c4',
    messagingSenderId: '165943096205',
    projectId: 'quickcarttdanyi',
    authDomain: 'quickcarttdanyi.firebaseapp.com',
    storageBucket: 'quickcarttdanyi.firebasestorage.app',
    measurementId: 'G-60VHP00S2S',
  );
}
